version: '3.7'

services:
  ############
  #  Django  #
  ############
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env.local
